version: '3.9'

services:
  mysql:
    image: mysql:8.1
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'

  redis:
    image: redis:8-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - '6379:6379'

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
    volumes:
      - ./:/var/www/html:cached
    ports:
      - '9000:9000'
    env_file: .env
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret
      REDIS_HOST: redis
      REDIS_PASSWORD: null
      REDIS_PORT: 6379
    depends_on:
      - mysql
      - redis

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./:/var/www/frontend:cached
      - /var/www/frontend/node_modules:cached
    ports:
      - '5173:5173'
    environment:
      VITE_APP_URL: http://localhost:5173
    depends_on:
      - app

volumes:
  mysql_data:
  redis_data:
